### ISSUE TITLE
'"ops" events are not supported by Loggly'

### ISSUE THREAD

**Issue by dsernst** [continuationlabs/good-loggly#11]
[`'"ops" events are not supported by Loggly'`](https://github.com/fhemberger/good-loggly/blob/master/lib/index.js#L23)

Can you offer more information about this?

**Comment by fhemberger** [comment]
Well, it's technically possible, but Loggly's focus is the analysis of request/error logs, not operational metrics (this would usually go into tools like Graphite, InfluxDB, etc.)

But you could modify this plug-in to send ops events as well.

**Comment by cjihrig** [comment]
I don't think we're going to implement this. It looks like Good is dropping the ops event - https://github.com/hapijs/good/issues/392.

**Comment by arb** [comment]
Just to clarify, the "ops" event isn't going to be removed, just the code responsible for creating it is going to be moved to another module.
