### ISSUE TITLE
Logging errors

### ISSUE THREAD

**Issue by AdriVanHoudt** [continuationlabs/good-loggly#12]
Atm logging errors (which is the main thing I want to do) is almost a no go.
Since the useful error values in js are not own properties (like message and stack) they do not get serialized.
2 options:
* provide own `getMessage` function which would kinda solve this.
* enhance the serialize process to allow errors to be logged (like https://github.com/logentries/le_node/blob/master/src/node_modules/serialize.js#L31)

**Comment by cjihrig** [comment]
I'm not going to make this the default behavior, but if you want to stringify `Error` objects, I just created this - https://www.npmjs.com/package/own2json

**Comment by AdriVanHoudt** [comment]
I don't expect it to be the default behaviour but it should be possible. And that is nice but then I need to modify Error.prototype ...
