### ISSUE TITLE
Add bulk messaging capability

### ISSUE THREAD

**Issue by PizzaBrandon** [continuationlabs/good-loggly#18]
Would you take a PR for adding bulk messaging support?

I recommend adding two options `threshold` and `maxDelay` like I used in [good-tcp](https://github.com/zefferus/good-tcp) which follows the pattern established by the official good plugins, such as [good-udp](https://github.com/hapijs/good-udp). These would inform the plugin if/how to buffer the messages before sending.

- `threshold` indicates how many messages to buffer before sending
- `maxDelay` tells the plugin the longest time it should hold a buffer before sending on next message (useful for programs with lower log frequency).

To maintain backward compatibility with existing plugin installations and make bulk transmission an opt-in feature, `threshold` would be set to `0`.

**Comment by PizzaBrandon** [comment]
Commit with code based on initial recommendation: https://github.com/PizzaBrandon/good-loggly/commit/dce400db7845617330f5e62c3e711a5bba96417d

**Comment by arb** [comment]
Sure, we'd take a PR for that feature.
